### ISSUE TITLE
BB runner improve message when docker is not running

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#1047]
```sh
error: Error: runner closed with exit code 125
    at ChildProcess.<anonymous> (/Users/davidgortega/Documents/projects/@iterative/cml/bin/cml/runner.js:276:37)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {"status":"terminated"}
info: Unregistering runner cml-c2ti2kx34n...
warn: SpotNotifier can not be started.
error:  Failed: docker stop cml-c2ti2kx34n

        Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

The error can be still be understood but could definitely be better

**Comment by dacbd** [comment]
the default docker error should be sufficient for now
