### ISSUE TITLE
Bitbucket is failing due to credentials

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#1245]
With a token with all the privileges enabled

```sh
cml send-comment --commit-sha $SHA --repo $REPO --token $REPO_TOKEN report.md 
info: Looking for PR associated with --commit-sha="3e062b8fcdf1109a009aa358eb843826b145e5f5".
See https://cml.dev/doc/ref/send-comment.
error: {
  err: Error: Bad Request Invalid Authorization header
      at BitbucketCloud.request /@iterative/cml/src/drivers/bitbucket_cloud.js:482:13)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async BitbucketCloud.paginatedRequest (/Users/davidgortega/Documents/projects/@iterative/cml/src/drivers/bitbucket_cloud.js:438:30)
      at async BitbucketCloud.commitPrs (/Users/davidgortega/Documents/projects/@iterative/cml/src/drivers/bitbucket_cloud.js:78:17)
      at async CML.commentCreate (/@iterative/cml/src/cml.js:269:31)
      at async Object.exports.handler (/@iterative/cml/bin/cml/send-comment.js:10:15)
}
```

however curl succeeds at least reading the commits with the same token

**Comment by DavidGOrtega** [comment]
Its fine. For some reason BB accepts the app token with header 'PRIVATE-TOKEN' in a subset of API calls 🤦 making me understand that I did not have to generate the tuple `name:pat`
