### ISSUE TITLE
cml comment create error on GitLab

### ISSUE THREAD

**Issue by l-kuo** [iterative/cml#1328]
Please see the error logs below.
```
> $ cat reports/metrics.json >> report.md
> $ echo '![](reports/confusion_testing.png "Confusion Matrix")' >> report.md
> $ cml comment create report.md
> {"level":"error","message":"Not Found","stack":"Error: Not Found\n    at Gitlab.request (/usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:553:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Gitlab.commitPrs (/usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:105:17)\n    at async parseCommentTarget (/usr/lib/node_modules/@dvcorg/cml/src/commenttarget.js:39:25)\n    at async CML.commentCreate (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:283:20)\n    at async Object.exports.handler (/usr/lib/node_modules/@dvcorg/cml/bin/cml/comment/create.js:11:15)"}
> Cleaning up file based variables
> 00:01
> ERROR: Job failed: exit code 1
> 

```

```

> $ cat reports/metrics.json >> report.md
> $ echo '![](reports/confusion_testing.png "Confusion Matrix")' >> report.md
> $ cml comment create --log=debug report.md
> {"level":"debug","message":"Gitlab API request, method: GET, url: \"https://gitlab-xxx.com/api/v4/version\""}
> {"level":"debug","message":"Gitlab API request, method: GET, url: \"https://gitlab-xxx.com/project/api/v4/version\""}
> {"level":"debug","message":"Response status is 404"}
> {"level":"debug","message":"Gitlab API request, method: GET, url: \"https://gitlab-xxx.com/api/v4/projects/project_repo/repository/commits/commit_num/merge_requests\""}
> {"level":"debug","message":"Response status is 404"}
> {"level":"debug","message":"Send analytics failed: Cannot read properties of undefined (reading 'startsWith')"}
> {"level":"error","message":"Not Found","stack":"Error: Not Found\n    at Gitlab.request (/usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:553:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Gitlab.commitPrs (/usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:105:17)\n    at async parseCommentTarget (/usr/lib/node_modules/@dvcorg/cml/src/commenttarget.js:39:25)\n    at async CML.commentCreate (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:283:20)\n    at async Object.exports.handler (/usr/lib/node_modules/@dvcorg/cml/bin/cml/comment/create.js:11:15)"}
> Cleaning up file based variables
> 00:01
> ERROR: Job failed: exit code 1
```

The above is my debug log.
Anyway, all the cml command are resulting in the same error. FYI, I am using custom built image with installed dvc and cml package. DVC is working fine but not cml part.

**Comment by DavidGOrtega** [comment]
👋 were you able to try as suggested in [discord](https://discord.com/channels/485586884165107732/728693131557732403/1068279184570450010) the api endpoint to see if it works?
 
```sh
curl -v -H "Authorization: Bearer $REPO_TOKEN" https://gitlab-aic.dynu.com/api/v4/version
```

As I stated the problem is the access to your self hosted gitlab instance

**Comment by l-kuo** [comment]
Yes, I tried according to suggestion and the API endpoint is working well.

**Comment by DavidGOrtega** [comment]
can you please paste the response 🙏  ?

**Comment by 0x2b3bfa0** [comment]
Context: as per discord#cml/1069545494277279845, the API endpoint is working correctly.

```console
$ curl -v -H "Authorization: Bearer [MASKED]" https://gitlab-aic.dynu.com/api/v4/version
{"version":"...","revision":"...", ..., "enterprise":true}
```

**Comment by tasdomas** [comment]
Is the `commit_num` entry in the request (from the debug log) corresponding to the head commit of the PR?
```
> {"level":"debug","message":"Gitlab API request, method: GET, url: \"https://gitlab-xxx.com/api/v4/projects/project_repo/repository/commits/commit_num/merge_requests\""}
```

**Comment by 0x2b3bfa0** [comment]
Yes, it's a well-formed URL like
```
https://gitlab-***.com/api/v4/projects/{group_name}%2F{project_name}/repository/commits/{long_commit_sha}/merge_requests/
```

**Comment by l-kuo** [comment]
> Can you please run this and send us the output?
> 
> ```
> curl -v -H "Authorization: Bearer $REPO_TOKEN" https://$HOST/api/v4/projects/$PROJECT/repository/commits/$COMMIT_HASH/merge_requests/
> ```

I sent it via discord message sir, thanks.

**Comment by tasdomas** [comment]
@0x2b3bfa0 - could you add the sanitized report to the issue?

**Comment by 0x2b3bfa0** [comment]
@l-kuo is using GitLab Enterprise Edition 15.6.1 [`fe39c71ac74`](https://gitlab.com/gitlab-org/gitlab/-/tree/fe39c71ac74e2a4b9c43fe8a24b07d4dc2b53caa) and has provided the result for the following queries:

### Using the project's percent-encoded normalized slug 🚫 
<code>https://<b>host</b>/api/v4/projects/<b>group</b>%2f<b>project</b></code>
```json
{"error":"404 Not Found"}
```

### Using the project's numeric identifier ✅ 
<code>https://<b>host</b>/api/v4/projects/<b>identifier</b></code>
```json
{...}
```

**Comment by 0x2b3bfa0** [comment]
The actual project and group names don't seem to have nothing to do with this issue, but the following API responses might shoed some light over the issue:

### Numeric identifiers
<code>https://<b>host</b>/api/v4/projects/<b>valid-identifier</b></code> ✅ 
```json
{...}
```
<code>https://<b>host</b>/api/v4/projects/<b>invalid-identifier</b></code> 🚫 
```json
{"message":"404 Project Not Found"}
```

### Slugs
<code>https://<b>host</b>/api/v4/projects/<b>valid-group</b>%2F<b>valid-project</b></code> ✅ 
```json
{...}
```
<code>https://<b>host</b>/api/v4/projects/<b>invalid-group</b>%2F<b>invalid-project</b></code> 🚫 
```json
{"message":"404 Project Not Found"}
```

### Malformed (slash not encoded)
<code>https://<b>host</b>/api/v4/projects/<b>valid-group</b>/<b>valid-project</b></code> 🚫 
```json
{"error":"404 Not Found"}
```
<code>https://<b>host</b>/api/v4/projects/<b>invalid-group</b>/<b>invalid-project</b></code> 🚫 
```json
{"error":"404 Not Found"}
```

**Comment by 0x2b3bfa0** [comment]
If some misconfigured proxy is turning url-encoded slashes into literal slashes, the URL suggested in https://github.com/iterative/cml/issues/1328#issuecomment-1422542598 should succeed.

**Comment by l-kuo** [comment]
> @l-kuo, do you also get a 404 error when navigating to `https://host/api/v4/projects/group%252Fproject`[1](#user-content-fn-1-2e5b718946aca2da540c6745c290af0a) on your browser?
> 
> ## Footnotes
> 1. Redacted with placeholders, sent the full URL on a Discord direct message. [leftwards_arrow_with_hook](#user-content-fnref-1-2e5b718946aca2da540c6745c290af0a)

Yes, it showed up {"message":"404 Project Not Found"}.

**Comment by 0x2b3bfa0** [comment]
@l-kuo, can you please confirm that https://github.com/iterative/cml/issues/1328#issuecomment-1422551159 is accurate?

* Request: <code>https://<b>host</b>/api/v4/projects/<b>group</b>%2F<b>project</b></code>
  * Response: `{"error":"404 Not Found"}`
* Request: <code>https://<b>host</b>/api/v4/projects/<b>group</b>%252F<b>project</b></code>
  * Response: `{"error":"404 Project Not Found"}`
* Request: <code>https://<b>host</b>/api/v4/projects/<b>number</b></code>
  * Response: project information

Note the difference between `Not Found` and `Project Not Found`

**Comment by l-kuo** [comment]
> @l-kuo, can you please confirm that [#1328 (comment)](https://github.com/iterative/cml/issues/1328#issuecomment-1422551159) is accurate?
> 
> * Request: `https://host/api/v4/projects/group%2Fproject`
>   
>   * Response: `{"error":"404 Not Found"}`
> * Request: `https://host/api/v4/projects/group%252Fproject`
>   
>   * Response: `{"error":"404 Project Not Found"}`
> * Request: `https://host/api/v4/projects/number`
>   
>   * Response: project information
> 
> Note the difference between `Not Found` and `Project Not Found`

Yes, this is absolutely correct response I got.

**Comment by 0x2b3bfa0** [comment]
@l-kuo, what output do you get after percent-encoding the whole repository slug?

Example: if the original URL is https://host/api/v4/projects/group%2Fproject, try https://host/api/v4/projects/%67%72%6f%75%70%25%32%46%70%72%6f%6a%65%63%74[^1] instead.

[^1]: You can use something like `printf %s "group%2Fproject"|xxd -p|tr -d \\n|sed s/../%\&/g` to convert it.

**Comment by l-kuo** [comment]
> @l-kuo, what output do you get after percent-encoding the whole repository slug?
> 
> Example: if the original URL is https://host/api/v4/projects/group%2Fproject, try https://host/api/v4/projects/%67%72%6f%75%70%25%32%46%70%72%6f%6a%65%63%74[1](#user-content-fn-1-0e9c899d1d57e0e154630ea6052c1299) instead.
> 
> ## Footnotes
> 1. You can use something like `printf %s "group%2Fproject"|xxd -p|tr -d \\n|sed s/../%\&/g` to convert it. [leftwards_arrow_with_hook](#user-content-fnref-1-0e9c899d1d57e0e154630ea6052c1299)

I got this output:

> 
{"message":"404 Project Not Found"}

**Comment by ziggy1209** [comment]
Hi there, I just encountered similar errors while trying to incoporate cml into my cicd.

**Comment by ziggy1209** [comment]
Hi there, I just encountered similar errors while trying to incoporate cml into my cicd.
```
$ cml comment create report.md
{"level":"error","message":"Not Found","stack":"Error: Not Found\n    at Gitlab.request (/usr/local/nodejs/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:584:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Gitlab.commitPrs (/usr/local/nodejs/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:111:17)\n    at async parseCommentTarget (/usr/local/nodejs/lib/node_modules/@dvcorg/cml/src/commenttarget.js:39:25)\n    at async CML.commentCreate (/usr/local/nodejs/lib/node_modules/@dvcorg/cml/src/cml.js:310:20)\n    at async Object.exports.handler (/usr/local/nodejs/lib/node_modules/@dvcorg/cml/bin/cml/comment/create.js:11:15)"}
```
and I still haven't got any clue.
