### ISSUE TITLE
Gitlab runner getting unregistered instantly after launch

### ISSUE THREAD

**Issue by julianjandeleit** [iterative/cml#1329]
We are launching cml with the following command:
```bash
docker run -e REPO_TOKEN=$TOKEN--network=$DOCKER_BRIDGE --mount type=bind,source=/mnt/data/dvc/,target=/data iterativeai/cml:latest-gpu runner launch --repo=$GITLAB_HTTPS_LINK --token=$TOKEN --driver=gitlab --labels=local,runner,ai-cli --idle-timeout -1
```
Directly after successfully connecting with our selfhosted gitlab instance, the runner gets stopped with the following output:
```json
{"level":"info","message":"Preparing workdir /home/runner..."}
{"level":"info","message":"Launching gitlab runner"}
{"level":"warn","message":"Error connecting to ACPI socket: connect ENOENT /var/run/acpid.socket. The acpid.service helps with instance termination detection."}
{"date":"2023-01-30T22:46:27.046Z","level":"info","message":"runner status","repo":"$GITLAB_HTTPS_LINK","status":"ready"}
{"level":"info","message":"Unregistering runner qtlelg56xp..."}
{"level":"info","message":"\tSuccess"}
{"date":"Mon Jan 30 2023 22:46:27 GMT+0000 (Coordinated Universal Time)","error":{},"exception":true,"level":"error","message":"unhandledRejection: runner closed with exit code 2\nError: runner closed with exit code 2\n    at ChildProcess.<anonymous> (/usr/lib/node_modules/@dvcorg/cml/bin/cml/runner/launch.js:322:37)\n    at ChildProcess.emit (node:events:513:28)\n    at maybeClose (node:internal/child_process:1100:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)","os":{"loadavg":[0.05,0.1,0.21],"uptime":8865075.96},"process":{"argv":["/usr/bin/node","/usr/bin/cml","runner","launch","$GITLAB_HTTPS_LINK","--token=$TOKEN","--driver=gitlab","--labels=local,runner,ai-cli","--idle-timeout","-1"],"cwd":"/home/runner","execPath":"/usr/bin/node","gid":0,"memoryUsage":{"arrayBuffers":5873467,"external":30257330,"heapTotal":60432384,"heapUsed":26755824,"rss":125382656},"pid":1,"uid":0,"version":"v16.19.0"},"stack":"Error: runner closed with exit code 2\n    at ChildProcess.<anonymous> (/usr/lib/node_modules/@dvcorg/cml/bin/cml/runner/launch.js:322:37)\n    at ChildProcess.emit (node:events:513:28)\n    at maybeClose (node:internal/child_process:1100:16)\n    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)","trace":[{"column":37,"file":"/usr/lib/node_modules/@dvcorg/cml/bin/cml/runner/launch.js","function":null,"line":322,"method":null,"native":false},{"column":28,"file":"node:events","function":"ChildProcess.emit","line":513,"method":"emit","native":false},{"column":16,"file":"node:internal/child_process","function":"maybeClose","line":1100,"method":null,"native":false},{"column":5,"file":"node:internal/child_process","function":"Process.ChildProcess._handle.onexit","line":304,"method":"onexit","native":false}]}
```
The output says _unhandledRejection: runner closed with exit code 2_. Two weeks ago, the runner was stable and picking up jobs as expected. What is being rejected here, and is this intentional?

**Comment by 0x2b3bfa0** [comment]
#### Minimal example

```console
$ npx github:iterative/cml#0d599b3 runner launch --repo=https://gitlab.com/$USER/$PROJECT --token=$TOKEN
info: Preparing workdir /home/codespace/.cml/jlpzi8i8ib...
info: Launching gitlab runner
warn: Error connecting to ACPI socket: connect ENOENT /var/run/acpid.socket. The acpid.service helps with instance termination detection.
info: runner status {"date":"2023-02-01T18:35:17.140Z","repo":"https://gitlab.com/$USER/$PROJECT","status":"ready"}
info: Unregistering runner jlpzi8i8ib...
info:   Success
error: unhandledRejection: runner closed with exit code 2
Error: runner closed with exit code 2
    at ChildProcess.<anonymous> (/home/codespace/.npm/_npx/419763917361aaed/node_modules/@dvcorg/cml/bin/cml/runner/launch.js:322:37)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Comment by 0x2b3bfa0** [comment]
@julianjandeleit, this error was caused by an upstream issue [gitlab-org/gitlab-runner#29592](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29592) introduced with GitLab Runner 15.8; we'll pin runners to the previous minor version until it's resolved.

**Comment by julianjandeleit** [comment]
Thanks a lot!

**Comment by 0x2b3bfa0** [comment]
For the record: opened [gitlab-org/gitlab-runner!3881](https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/3881) with an upstream fix.
