### ISSUE TITLE
Bug: CML can't be installed from npm due to "@npcz/magic" not being installable

### ISSUE THREAD

**Issue by Taytay** [iterative/cml#1401]
Just started getting this in the past 24 hours on my build machine. (As in, it worked 24 hours ago, and today as of 30 minutes ago, it does not.)

This is odd. See full debug info below.
Looks like the package `@npcz/magic` is not installable at present:
https://www.npmjs.com/package/@npcz/magic

Can't even run `npm i -g @npcz/magic`:
```
❯ npm i -g @npcz/magic
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@npcz%2fmagic - Not found
npm ERR! 404
npm ERR! 404  '@npcz/magic@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Will open an issue on their repo too. Not sure what is happening.
```
npm i --verbose -g @dvcorg/cml
npm verb cli /opt/homebrew/Cellar/node/20.4.0/bin/node /opt/homebrew/bin/npm
npm info using npm@9.7.2
npm info using node@v20.4.0
npm verb title npm i @dvcorg/cml
npm verb argv "i" "--loglevel" "verbose" "--global" "@dvcorg/cml"
npm verb logfile logs-max:10 dir:/Users/taytay/.npm/_logs/2023-07-14T20_12_33_241Z-
npm verb logfile /Users/taytay/.npm/_logs/2023-07-14T20_12_33_241Z-debug-0.log
npm http fetch GET 200 https://registry.npmjs.org/@dvcorg%2fcml 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/chokidar 47ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@actions%2fgithub 49ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/exponential-backoff 48ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/form-data 48ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/colors 48ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2fplugin-throttling 50ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/getos 48ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2fgraphql 51ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/appdirs 52ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2frest 52ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/https-proxy-agent 53ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-docker 53ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/globby 54ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fs-extra 54ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/kebabcase-keys 54ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/js-base64 55ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/git-url-parse 56ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/proxy-agent 54ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/node-fetch 56ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/os-name 56ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/node-ssh 57ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/remark 57ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/pseudoexec 58ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/strip-ansi 56ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-git 56ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/semver 59ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/unist-util-visit 56ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tar 58ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tempy 58ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/uuid 58ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@actions%2fcore 68ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/timestring 59ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/strip-url-auth 61ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2fcore 68ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/which 61ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/winston 62ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/yargs 63ms (cache hit)
npm http fetch GET 404 https://registry.npmjs.org/@npcz%2fmagic 238ms (cache skip)
npm http fetch GET 404 https://registry.npmjs.org/@npcz%2fmagic 52ms (cache skip)
npm http fetch GET 200 https://registry.npmjs.org/encoding 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@actions%2fhttp-client 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2fplugin-rest-endpoint-methods 97ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@actions%2fhttp-client 109ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/universal-user-agent 107ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2frequest-error 107ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2fauth-token 108ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2fplugin-rest-endpoint-methods 110ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/before-after-hook 110ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2fplugin-paginate-rest 104ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/glob-parent 102ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/braces 104ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2frequest 113ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2ftypes 108ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2fplugin-paginate-rest 117ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/readdirp 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-binary-path 107ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/anymatch 109ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/normalize-path 108ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2ftypes 117ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/combined-stream 108ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/jsonfile 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/asynckit 108ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/graceful-fs 107ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mime-types 108ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/async 107ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fsevents 111ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2fplugin-request-log 114ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/array-union 107ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ignore 105ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/debug 105ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/merge2 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/dir-glob 108ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/git-up 109ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-glob 114ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/universalify 110ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/slash 108ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/shell-escape 102ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/lodash.kebabcase 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-stream 103ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2frequest 123ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/bottleneck 120ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/make-dir 105ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/agent-base 109ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/whatwg-url 109ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/http-proxy-agent 104ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/sb-scandir 107ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/windows-release 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/map-obj 111ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/proxy-from-env 104ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fast-glob 114ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ssh2 108ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/unified 104ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/macos-release 108ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/socks-proxy-agent 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ansi-regex 103ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/minizlib 101ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/remark-parse 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/pac-proxy-agent 107ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/chownr 103ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@kwsites%2fpromise-deferred 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/lru-cache 109ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/temp-dir 102ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/sb-promise-queue 112ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/unique-string 101ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/async 99ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fs-minipass 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@types%2funist 101ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@kwsites%2ffile-exists 108ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/yallist 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/remark-stringify 110ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/agent-base 112ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mkdirp 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/isexe 102ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/quick-lru 119ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/at-least-node 125ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/readable-stream 100ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/logform 101ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/type-fest 105ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/unist-util-is 105ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/stack-trace 101ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/minipass 109ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/one-time 103ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/string-width 101ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@colors%2fcolors 105ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/require-directory 102ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/winston-transport 103ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/safe-stable-stringify 104ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/debug 114ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/unist-util-visit-parents 108ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@dabh%2fdiagnostics 106ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/triple-beam 104ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/escalade 103ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/get-caller-file 104ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/cliui 104ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/y18n 103ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/yargs-parser 103ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tunnel 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/deprecation 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2fendpoint 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-plain-object 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/once 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@octokit%2fopenapi-types 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/wrappy 1ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/picomatch 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/binary-extensions 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/picomatch 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-extglob 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fill-range 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/to-regex-range 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-number 1ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/delayed-stream 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mime-db 1ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-ssh 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/parse-url 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/protocols 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/parse-path 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/micromatch 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@nodelib%2ffs.walk 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@nodelib%2ffs.stat 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/path-type 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@nodelib%2ffs.scandir 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fastq 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/reusify 1ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/run-parallel 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/queue-microtask 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ms 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/webidl-conversions 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tr46 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/asn1 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/cpu-features 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/bcrypt-pbkdf 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/nan 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/execa 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@tootallnate%2fonce 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/raw-body 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/pac-resolver 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/get-uri 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/socks 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ip 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/file-uri-to-path 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ftp 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/degenerator 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/bytes 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/data-uri-to-buffer 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/iconv-lite 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/unpipe 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/http-errors 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/netmask 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/xregexp 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/isarray 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/inherits 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/core-util-is 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/string_decoder 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/escodegen 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/esprima 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/vm2 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ast-types 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tslib 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/estraverse 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/esutils 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/optionator 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/acorn 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/source-map 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/acorn-walk 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/prelude-ls 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/word-wrap 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/type-check 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fast-levenshtein 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/deep-is 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/levn 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/depd 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/safer-buffer 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/setprototypeof 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/toidentifier 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/statuses 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-plain-obj 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mdast-util-to-markdown 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/extend 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mdast-util-from-markdown 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/trough 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-buffer 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/bail 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/vfile 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mdast-util-to-string 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/parse-entities 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/micromark 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@types%2fmdast 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/unist-util-stringify-position 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/character-entities 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/character-entities-legacy 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/character-reference-invalid 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-alphanumerical 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-hexadecimal 9ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-decimal 10ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-alphabetical 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/repeat-string 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/longest-streak 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/zwitch 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/smart-buffer 1ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/buildcheck 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/tweetnacl 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/crypto-random-string 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/vfile-message 1ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/onetime 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/cross-spawn 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/npm-run-path 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/merge-stream 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/get-stream 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/human-signals 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/strip-final-newline 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/signal-exit 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/path-key 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/shebang-command 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/path-key 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/mimic-fn 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/shebang-regex 1ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/colorspace 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/enabled 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@types%2ftriple-beam 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/kuler 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/util-deprecate 5ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fn.name 7ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/fecha 8ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/text-hex 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-string 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-convert 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-name 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/color-name 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/simple-swizzle 3ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-arrayish 1ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/wrap-ansi 6ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/emoji-regex 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/is-fullwidth-code-point 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/ansi-styles 2ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/@types%2fnode 4ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/safe-buffer 3ms (cache hit)
npm verb stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@npcz%2fmagic - Not found
npm verb stack     at /opt/homebrew/lib/node_modules/npm/node_modules/npm-registry-fetch/lib/check-response.js:95:15
npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verb stack     at async RegistryFetcher.packument (/opt/homebrew/lib/node_modules/npm/node_modules/pacote/lib/registry.js:87:19)
npm verb stack     at async RegistryFetcher.manifest (/opt/homebrew/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:23)
npm verb stack     at async Promise.all (index 2)
npm verb stack     at async #buildDepStep (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1034:5)
npm verb stack     at async Arborist.buildIdealTree (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
npm verb stack     at async Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
npm verb stack     at async Install.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/install.js:149:5)
npm verb stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli-entry.js:61:5)
npm verb statusCode 404
npm verb pkgid @npcz/magic@^1.3.12
npm verb cwd /Users/taytay/projects/YNAB/evergreen
npm verb Darwin 22.5.0
npm verb node v20.4.0
npm verb npm  v9.7.2
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@npcz%2fmagic - Not found
npm ERR! 404
npm ERR! 404  '@npcz/magic@^1.3.12' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit 1
npm verb unfinished npm timer reify 1689365553366
npm verb unfinished npm timer reify:loadTrees 1689365553368
npm verb code 1
```

**Comment by Taytay** [comment]
Works like a champ now. Just a hiccupt
