### ISSUE TITLE
cml comment create is giving unauthorization error

### ISSUE THREAD

**Issue by bhaswa** [iterative/cml#1464]
When I use the command in gitlab ci/cd pipeline, getting the below error

cml comment create  report.md

{"level":"warn","message":"\"cml send-comment\" is deprecated, please use \"cml comment create\""}
{"level":"error","message":"Unauthorized","stack":"Error: Unauthorized\n    at Gitlab.request (/usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:573:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:54:16\n    at async Promise.all (index 0)\n    at async Gitlab.repoBase (/usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:45:27)\n    at async Gitlab.projectPath (/usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:33:22)\n    at async Gitlab.commitPrs (/usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:108:25)\n    at async parseCommentTarget (/usr/lib/node_modules/@dvcorg/cml/src/commenttarget.js:39:25)\n    at async CML.commentCreate (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:308:20)\n    at async Object.exports.handler (/usr/lib/node_modules/@dvcorg/cml/bin/cml/comment/create.js:11:15)"}

**Comment by 0x2b3bfa0** [comment]
Hello, @bhaswa! Please make sure that your token is valid.

**Comment by Chapi15** [comment]
I have the same error for the GitHub Actions pipeline
