### ISSUE TITLE
no Security Groups found

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#447]
```sh
Error: Failed creating the machine: no Security Groups found
    at /cml/src/utils.js:15:27
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
iterative_cml_runner.runner: Destroying... [id=iterative-Ua1WWLUDp]
iterative_cml_runner.runner: Destruction complete after 1s
```

**Comment by DavidGOrtega** [comment]
Seems to be an AWS bug?
In terraform-provider-iterative ```len(sgDesc.SecurityGroups)``` is returning 0 despite that I have 4 in that region.

![image](https://user-images.githubusercontent.com/414967/111139895-f86b7780-8581-11eb-9f5f-c265a178b265.png)

**Comment by 0x2b3bfa0** [comment]
From [CreateSecurityGroup](https://github.com/iterative/terraform-provider-iterative/blob/d7c81bd160f36754482189354b319656cec0d6d0/iterative/aws/provider.go#L105-L109) at [iterative/aws/provider.go:105](https://github.com/iterative/terraform-provider-iterative/blob/d7c81bd160f36754482189354b319656cec0d6d0/iterative/aws/provider.go#L105-L109)

```console
UnauthorizedOperation: You are not authorized to perform this operation. Authorization failure message:
```
```json
{
  "allowed": false,
  "explicitDeny": false,
  "matchedStatements": {
    "items": []
  },
  "failures": {
    "items": []
  },
  "context": {
    "principal": {
      "id": "···",
      "name": "dvc-cml-terraform-provider",
      "arn": "arn:aws:iam::···:user/···"
    },
    "action": "ec2:CreateSecurityGroup",
    "resource": "arn:aws:ec2:us-west-1:···:vpc/vpc-···",
    "conditions": {
      "items": [
        {
          "key": "aws:Region",
          "values": {
            "items": [
              {
                "value": "us-west-1"
              }
            ]
          }
        },
        {
          "key": "aws:Service",
          "values": {
            "items": [
              {
                "value": "ec2"
              }
            ]
          }
        },
        {
          "key": "aws:Resource",
          "values": {
            "items": [
              {
                "value": "vpc/vpc-···"
              }
            ]
          }
        },
        {
          "key": "aws:Account",
          "values": {
            "items": [
              {
                "value": "···"
              }
            ]
          }
        },
        {
          "key": "aws:Type",
          "values": {
            "items": [
              {
                "value": "vpc"
              }
            ]
          }
        },
        {
          "key": "ec2:Tenancy",
          "values": {
            "items": [
              {
                "value": "default"
              }
            ]
          }
        },
        {
          "key": "ec2:VpcID",
          "values": {
            "items": [
              {
                "value": "vpc-···"
              }
            ]
          }
        },
        {
          "key": "ec2:Region",
          "values": {
            "items": [
              {
                "value": "us-west-1"
              }
            ]
          }
        },
        {
          "key": "aws:ARN",
          "values": {
            "items": [
              {
                "value": "arn:aws:ec2:us-west-1:···:vpc/vpc-···"
              }
            ]
          }
        }
      ]
    }
  }
}
```

**Comment by 0x2b3bfa0** [comment]
```console
$ AWS_REGION=us-west-1 aws ec2 describe-security-groups
{
    "SecurityGroups": [
        {
            "Description": "CML security group",
            "GroupName": "cml",
            "IpPermissions": [···],
            "OwnerId": "···",
            "GroupId": "sg-···",
            "IpPermissionsEgress": [···],
            "VpcId": "vpc-···"
        }
    ]
}
```

**Comment by DavidGOrtega** [comment]
> Seems to be an AWS bug?
In terraform-provider-iterative len(sgDesc.SecurityGroups) is returning 0 despite that I have 4 in that region.

I can see that Iterative !== iterative 🤔

**Comment by 0x2b3bfa0** [comment]
Good catch! I was going to comment the same a few seconds ago.

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, is that screenshot above from the `us-west-1` region?

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 My personal us-west-1

I think that aws has lots of issues with upper case. They are creating sometimes things with Upper and then is not searchable with lower.

I.E. Im able to change ```iterative``` group name to ```Iterative``` the latest is not going to be created probably because coincides with iterative but its not going to be found because  Iterative !== iterative
Looks like a discrepancy between creation and searching

**Comment by DavidGOrtega** [comment]
Exactly as I said

```
Failed creating the machine: Not able to decode: InvalidGroup.Duplicate: The security group 'Iterative' already exists for VPC 'vpc-32110855'
        status code: 400, request id: 0763a44b-0a39-4072-ac7d-311a8c78d2a3
```

however is not able to find it with Iterative since its iterative 😅

**Comment by 0x2b3bfa0** [comment]
It looks similar to https://github.com/chef-boneyard/chef-provisioning-aws/issues/452 🤔

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, the GitLab continuous integration jobs are still failing. Shall we reopen this issue?

**Comment by 0x2b3bfa0** [comment]
Reopened and requested permissions as per the prior art on https://github.com/iterative/cml/issues/429

**Comment by DavidGOrtega** [comment]
Why reopened? We have fix the issue. Now we should have seen permission denial instead of no Security Groups found

**Comment by 0x2b3bfa0** [comment]
I reopened it because of the same error on GitLab, but it was fixed by granting ourselves the required permissions with  iterative/viewer-itops#4. Closing again...
