### ISSUE TITLE
@actions/http-client MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#460]
seen in [discord](https://discord.com/channels/485586884165107732/728693131557732403/824582211469836320)

```yaml
Run cml-runner \
  cml-runner \
  --cloud aws \
  --cloud-region eu-west-1 \
  --cloud-type=p3.2xlarge \
  --cloud-hdd-size 64 \
  --cloud-spot \
  --labels=cml-runner
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    repo_token: ***
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
```

```sh
internal/modules/cjs/loader.js:311
      throw err;
Error: Cannot find module '/usr/local/lib/node_modules/@dvcorg/cml/node_modules/@actions/http-client/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@dvcorg/cml/node_modules/@actions/github/lib/internal/utils.js:23:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/usr/local/lib/node_modules/@dvcorg/cml/node_modules/@actions/http-client/package.json',
  requestPath: '@actions/http-client'
}
Error: Process completed with exit code 1.
```

**Comment by 0x2b3bfa0** [comment]
@DavidGOrtega, it looks like this was some sort of transient issue that we can't fix nor reproduce. Should we close it?

**Comment by 0x2b3bfa0** [comment]
In fact, https://github.com/oap-project/native-sql-engine/issues/200 also seems to be fixed and closed.

**Comment by DavidGOrtega** [comment]
@0x2b3bfa0 lets close it! Not sure why this issue is related to the other

**Comment by 0x2b3bfa0** [comment]
It looks like oap-project/native-sql-engine#200 is exactly the same issue, as shown in the linked GitHub Actions logs. Anyways.
