### ISSUE TITLE
cml-send-comment fatal: not a git repository

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#478]
If cml-send-command is not in a folder init with git:

```sh
Error: git rev-parse HEAD

        fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

    at /iterative/cml/src/utils.js:15:27
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```

**Comment by 0x2b3bfa0** [comment]
Closed with #517
