### ISSUE TITLE
cml-publish does not support basic text files

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#518]
Reproduce it:

```sh
echo Hello > world.txt
cml-publish --repo=https://github.com/DavidGOrtega/cml-dvc-test world.txt

Error: Failed guessing mime type of file world.txt
    at mime_type (/iterative/cml/src/utils.js:49:11)
    at async fetch_upload_data (/iterative/cml/src/utils.js:60:16)
    at async upload (/iterative/cml/src/utils.js:69:38)
    at async CML.publish (/iterative/cml/src/cml.js:110:24)
    at async run (/iterative/cml/bin/cml-publish.js:25:18)
```

**Comment by 0x2b3bfa0** [comment]
Closed with #519
