### ISSUE TITLE
github cache sometimes fails when building the images

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#546]
```sh
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/cml/cml --files-from manifest.txt
Warning: Cache service responded with 429 during upload chunk.
/home/runner/work/_actions/actions/cache/v2/dist/save/index.js:4043
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/home/runner/work/_actions/actions/cache/v2/dist/save/index.js:4043:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

![image](https://user-images.githubusercontent.com/414967/118961572-bfc29280-b964-11eb-9725-fdc6648ae44f.png)

**Comment by 0x2b3bfa0** [comment]
#1158081

**Comment by 0x2b3bfa0** [comment]
It won't happen again, according to GitHub. There isn't any documented limit apart from the 5GB one, and this was a transient issue.
