### ISSUE TITLE
cml-pr fails with `Validation Failed: {"resource":"PullRequest","field":"base","code":"invalid"}`

### ISSUE THREAD

**Issue by aguschin** [iterative/cml#619]
Running `cml-pr` fails (tried both with `secrets.GITHUB_TOKEN` and personal access token).
Logs:

```
2021-06-29T10:15:49.6395304Z RequestError [HttpError]: Validation Failed: {"resource":"PullRequest","field":"base","code":"invalid"}
2021-06-29T10:15:49.6398651Z     at /usr/lib/node_modules/@dvcorg/cml/node_modules/@octokit/request/dist-node/index.js:86:21
2021-06-29T10:15:49.6402708Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-06-29T10:15:49.6404764Z     at async Github.prCreate (/usr/lib/node_modules/@dvcorg/cml/src/drivers/github.js:276:9)
2021-06-29T10:15:49.6406369Z     at async CML.prCreate (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:318:17)
2021-06-29T10:15:49.6408484Z     at async run (/usr/lib/node_modules/@dvcorg/cml/bin/cml-pr.js:14:10) {
2021-06-29T10:15:49.6409483Z   status: 422,
2021-06-29T10:15:49.6410192Z   response: {
2021-06-29T10:15:49.6411776Z     url: 'https://api.github.com/repos/iterative/yolov5/pulls',
2021-06-29T10:15:49.6412943Z     status: 422,
2021-06-29T10:15:49.6413703Z     headers: {
2021-06-29T10:15:49.6415305Z       'access-control-allow-origin': '*',
2021-06-29T10:15:49.6419256Z       'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
2021-06-29T10:15:49.6421838Z       connection: 'close',
2021-06-29T10:15:49.6422564Z       'content-length': '190',
2021-06-29T10:15:49.6423493Z       'content-security-policy': "default-src 'none'",
2021-06-29T10:15:49.6424548Z       'content-type': 'application/json; charset=utf-8',
2021-06-29T10:15:49.6425385Z       date: 'Tue, 29 Jun 2021 10:15:49 GMT',
2021-06-29T10:15:49.6426665Z       'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
2021-06-29T10:15:49.6427894Z       server: 'GitHub.com',
2021-06-29T10:15:49.6428990Z       'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
2021-06-29T10:15:49.6430247Z       vary: 'Accept-Encoding, Accept, X-Requested-With',
2021-06-29T10:15:49.6431234Z       'x-accepted-oauth-scopes': '',
2021-06-29T10:15:49.6432174Z       'x-content-type-options': 'nosniff',
2021-06-29T10:15:49.6433000Z       'x-frame-options': 'deny',
2021-06-29T10:15:49.6433888Z       'x-github-media-type': 'github.v3; format=json',
2021-06-29T10:15:49.6435068Z       'x-github-request-id': 'E546:26A9:4BE5B:896C20:60DAF2D5',
2021-06-29T10:15:49.6436146Z       'x-oauth-scopes': 'repo, workflow',
2021-06-29T10:15:49.6436949Z       'x-ratelimit-limit': '5000',
2021-06-29T10:15:49.6437750Z       'x-ratelimit-remaining': '4999',
2021-06-29T10:15:49.6438582Z       'x-ratelimit-reset': '1624965349',
2021-06-29T10:15:49.6439405Z       'x-ratelimit-resource': 'core',
2021-06-29T10:15:49.6440203Z       'x-ratelimit-used': '1',
2021-06-29T10:15:49.6440925Z       'x-xss-protection': '0'
2021-06-29T10:15:49.6441391Z     },
2021-06-29T10:15:49.6441757Z     data: {
2021-06-29T10:15:49.6442415Z       message: 'Validation Failed',
2021-06-29T10:15:49.6443183Z       errors: [Array],
2021-06-29T10:15:49.6444468Z       documentation_url: 'https://docs.github.com/rest/reference/pulls#create-a-pull-request'
2021-06-29T10:15:49.6445369Z     }
2021-06-29T10:15:49.6445770Z   },
2021-06-29T10:15:49.6446157Z   request: {
2021-06-29T10:15:49.6446754Z     method: 'POST',
2021-06-29T10:15:49.6447967Z     url: 'https://api.github.com/repos/iterative/yolov5/pulls',
2021-06-29T10:15:49.6449045Z     headers: {
2021-06-29T10:15:49.6450322Z       accept: 'application/vnd.github.v3+json',
2021-06-29T10:15:49.6451638Z       'user-agent': 'octokit-core.js/3.5.1 Node.js/12.22.1 (linux; x64)',
2021-06-29T10:15:49.6453045Z       authorization: 'token [REDACTED]',
2021-06-29T10:15:49.6454323Z       'content-type': 'application/json; charset=utf-8'
2021-06-29T10:15:49.6454999Z     },
2021-06-29T10:15:49.6457896Z     body: '{"head":"refs/pull/8/merge-cml-pr-b4afd3dc","base":"refs/pull/8/merge","title":"CML PR for refs/pull/8/merge b4afd3dc","body":"\\nAutomated commits for https://github.com/iterative/yolov5/commit/b4afd3dcbb518e652301418a8c2d32140806c54f created by CML.\\n  "}',
2021-06-29T10:15:49.6459793Z     request: { agent: [Agent], hook: [Function: bound bound register] }
2021-06-29T10:15:49.6460446Z   }
2021-06-29T10:15:49.6460856Z }
```

Full logs could be seen here: https://github.com/iterative/yolov5/runs/2940960716?check_suite_focus=true

**Comment by DavidGOrtega** [comment]
Its trying to use a wrong base ```"base":"refs/pull/8/merge"```

**Comment by 0x2b3bfa0** [comment]
I think that pull references are valid on GitHub 🤔

**Comment by 0x2b3bfa0** [comment]
Workflows triggered with the [`pull_request`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request) GitHub Actions event are going to have [`github.ref`](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context) set to one of the [pull references](https://git-scm.com/book/id/v2/GitHub-Maintaining-a-Project#_pr_refs) that GitHub creates for pull requests. We haven't noticed until now because all the tests were made using the [`push`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push) event.

We only consider `heads` and `tags` references and remove the first path components with a regular expression, and it works pretty well for these two kinds of references, but fails for the `pull` ones:
https://github.com/iterative/cml/blob/6c451d965aaea2ad2b1812dd2a223def9ce87739/src/drivers/github.js#L24

The most elegant solution I can think of would using a [short-circuit evaluation](https://en.wikipedia.org/wiki/Short-circuit_evaluation) fallback to [`GITHUB_HEAD_REF || GITHUB_REF`](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables) here:
https://github.com/iterative/cml/blob/6c451d965aaea2ad2b1812dd2a223def9ce87739/src/drivers/github.js#L321
https://github.com/iterative/cml/blob/6c451d965aaea2ad2b1812dd2a223def9ce87739/src/drivers/github.js#L14-L19

***

⚠️ Disclaimer: untested hypothesis; if it looks reasonable enough, I'll test it and open a pull request.

**Comment by aguschin** [comment]
Awesome, thank you! Just checked and it works!
