### ISSUE TITLE
Infinite TB loop

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#647]
Somehow TB can loop forever instead of just failing. This is terrible for cloud instances.

```sh
(node:1809) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
    at Timeout._onTimeout (/usr/lib/node_modules/@dvcorg/cml/bin/cml-tensorboard-dev.js:71:17)
(node:1809) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1809) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1809) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
    at Timeout._onTimeout (/usr/lib/node_modules/@dvcorg/cml/bin/cml-tensorboard-dev.js:71:17)
(node:1809) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1809) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of null
    at Timeout._onTimeout (/usr/lib/node_modules/@dvcorg/cml/bin/cml-tensorboard-dev.js:71:17)
(node:1809) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

**Comment by 0x2b3bfa0** [comment]
Related to / duplicate of #479?

**Comment by DavidGOrtega** [comment]
Maybe related, however this error is different, in that occasion the error came just fine, here is trapped inside an infinite loop
