### ISSUE TITLE
DVC doctor reveals missing adlfs package in latest CML image

### ISSUE THREAD

**Issue by mattlbeck** [iterative/cml#692]
I know this is a DVC issue, but it only occurs in the latest CML image.

```
> dvc doctor
ERROR: unexpected error - adlfs
Traceback (most recent call last):
  File "dvc/main.py", line 55, in main
  File "dvc/command/base.py", line 64, in do_run
  File "dvc/command/version.py", line 14, in run
  File "dvc/info.py", line 35, in get_dvc_info
  File "dvc/info.py", line 127, in _get_supported_remotes
  File "importlib/metadata.py", line 531, in version
  File "importlib/metadata.py", line 504, in distribution
  File "importlib/metadata.py", line 177, in from_name
importlib.metadata.PackageNotFoundError: adlfs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dvc/__main__.py", line 7, in <module>
  File "dvc/main.py", line 88, in main
  File "dvc/info.py", line 35, in get_dvc_info
  File "dvc/info.py", line 127, in _get_supported_remotes
  File "importlib/metadata.py", line 531, in version
  File "importlib/metadata.py", line 504, in distribution
  File "importlib/metadata.py", line 177, in from_name
importlib.metadata.PackageNotFoundError: adlfs
[404] Failed to execute script __main__

> dvc --version
2.5.4

> cml-runner --version
0.6.3
```

A `pip install dvc adlfs` does **not** fix the problem 🤔

**Comment by 0x2b3bfa0** [comment]
The DVC builds we ship as part of the CML container images are standalone `pyinstaller` binaries with no dependency on the system's Python installation. That's probably why running `pip install` has no effect.

🔔 @iterative/dvc, is this a known issue?

**Comment by efiop** [comment]
@0x2b3bfa0 Looks like maybe our pyinstaller hook broke or something. Investigating...

**Comment by 0x2b3bfa0** [comment]
🙏🏼 Thank you very much, @efiop!

**Comment by efiop** [comment]
For the record: 2.6.0 will be released today/tomorrow.

**Comment by 0x2b3bfa0** [comment]
@mattlbeck, in the worst case scenario, fixes should propagate to container images 24 hours after the release of DVC 2.6.0, but I'll try to stay tuned and trigger a manual image rebuild as soon as possible.

**Comment by 0x2b3bfa0** [comment]
@mattlbeck, fixed!
