### ISSUE TITLE
cml-tensorboard-dev return failed: Tensorboard process exited with code

### ISSUE THREAD

**Issue by quyetvk** [iterative/cml#702]
Hi,

I try to use tensorboard with CML. I build my environment based on:
https://gitlab.com/iterative.ai/cml-tensorboard-case/-/tree/master

But I've got following error:

```
 cml-tensorboard-dev --logdir logs --md --name "Go to tensorboard" >> report.md
/cml/bin/cml-tensorboard-dev.js:62
    throw new Error(`Tensorboard process exited with code ${code}`);
    ^
Error: Tensorboard process exited with code 1
    at ChildProcess.<anonymous> (/cml/bin/cml-tensorboard-dev.js:62:11)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
```

Could you please support me?

Thanks in advance!

**Comment by quyetvk** [comment]
Sorry, it is my mistake. I have not yet setup variables correctly.
I solved problem by myself.
I closed the issue.
