### ISSUE TITLE
Legacy cml-command syntax broken on Windows

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/cml#736]
```
const [, base, command] = basename(file).match(/^(\w+)-(.+)$/);
                          ^

TypeError: basename is not iterable (cannot read property Symbol(Symbol.iterator))
    at Object.<anonymous> (D:\a\cml\cml\bin\legacy.js:12:27)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

NPM uses [`cmd-shim`](https://www.npmjs.com/package/cmd-shim) on Windows instead of creating symbolic links.  This shim consists of a [hardcoded script](https://github.com/npm/cmd-shim/blob/5b3eaa39fd085fe4209a2c39bf05b6d01bd34956/index.js#L128) that calls the executables specified on [`package.json:bin`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#bin) with the `node` interpreter, and, because of the indirect call, [`$0`](https://www.gnu.org/software/bash/manual/bash.html#index-0) gets lost in the process.

https://github.com/iterative/cml/blob/7d664aec00023e8fba48e660f2f8e184477d8cdd/bin/legacy.js#L11-L12

Because of this, `basename(file)` equals `legacy.js` instead of `cml-command` as expected. Therefore, `/^(\w+)-(.+)$/` doesn't match anything (obviously) and we don't have any means to determine which legacy command was called.

**Comment by 0x2b3bfa0** [comment]
This only affects **legacy** commands on Windows, and doesn't have any ~easy~ realistic solution. Should we just ignore it?

**Comment by 0x2b3bfa0** [comment]
:bell: @iterative/cml, voting to close without changes through #737

**Comment by 0x2b3bfa0** [comment]
https://github.com/npm/documentation/issues/39
