### ISSUE TITLE
`cml send-comment` fails in BB without existing PRs

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#807]
```sh
{"level":"error","message":"invalid json response body at https://api.bitbucket.org/2.0/repositories/DavidOrtega%2Ffashion-mnist/commit/046780cb574ff969bcf48888b16044ba15141dce/pullrequests?state=OPEN reason: Unexpected end of JSON input","stack":"FetchError: invalid json response body at https://api.bitbucket.org/2.0/repositories/DavidOrtega%2Ffashion-mnist/commit/046780cb574ff969bcf48888b16044ba15141dce/pullrequests?state=OPEN reason: Unexpected end of JSON input\n    at /usr/lib/node_modules/@dvcorg/cml/node_modules/node-fetch/lib/index.js:273:32\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async BitbucketCloud.request (/usr/lib/node_modules/@dvcorg/cml/src/drivers/bitbucket_cloud.js:245:11)\n    at async BitbucketCloud.paginatedRequest (/usr/lib/node_modules/@dvcorg/cml/src/drivers/bitbucket_cloud.js:258:30)\n    at async BitbucketCloud.commitPrs (/usr/lib/node_modules/@dvcorg/cml/src/drivers/bitbucket_cloud.js:71:19)\n    at async CML.commentCreate (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:132:31)\n    at async Object.exports.handler (/usr/lib/node_modules/@dvcorg/cml/bin/cml/send-comment.js:13:15)","type":"invalid-json"}
```

**Comment by DavidGOrtega** [comment]
Also
```sh
k-Pro:fashion_mnist davidgortega$ cml send-comment --repo https://bitbucket.org/DavidOrtega/python-mnist --token XXXX --commit-sha 4ea3e45f656c427907aa8911f99ca1eec8787f77 report.md
error: Click 'Go to pull request' on any commit details page to enable this API
```
