### ISSUE TITLE
`cml send-comment --update`: Raises 'commit_id has been locked' error

### ISSUE THREAD

**Issue by daavoo** [iterative/cml#888]
When calling `cml send-comment --update` from a python script using `subprocess.run`, the following error is being raised:

```
"HttpError: Validation Failed: {\"resource\":\"CommitComment\",\"code\":\"custom\",\"field\":\"commit_id\",\"message\":\"commit_id has been locked\"}
    at /usr/lib/node_modules/@dvcorg/cml/node_modules/@octokit/request/dist-node/index.js:86:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Job.doExecute (/usr/lib/node_modules/@dvcorg/cml/node_modules/bottleneck/light.js:405:18)","status":422}
```

Without `--update`, the error is not being raised.

Code:

```python
import subprocess

for i in range(3):
    with open("report.md", "w") as f:
        f.write(f"## {i}")
    
    subprocess.run(
        ["cml", "send-comment", "--update", "report.md"],
        check=True
    )
```

Example failure:
https://github.com/iterative/test-cml-send-comment-pr/runs/5036525998?check_suite_focus=true#step:4:7

**Comment by casperdcl** [comment]
Potentially just recent issue with GH being down again? Is it still not working?

**Comment by daavoo** [comment]
> Potentially just recent issue with GH being down again? Is it still not working?

It is still failing https://github.com/iterative/test-cml-send-comment-pr/runs/5049305678?check_suite_focus=true#step:4:6 

Note that removing `--uptade` option makes the error disappear, so that same script is able to post multiple comments on same commit but not update a single one.

**Comment by DavidGOrtega** [comment]
@daavoo how often do you call it? Might be an error in their queue. Try to slowdown the call just to try to see what happens.

**Comment by daavoo** [comment]
> @daavoo how often do you call it? Might be an error in their queue. Try to slowdown the call just to try to see what happens.

I have added `time.sleep(10)` between calls but still fails: 

https://github.com/iterative/test-cml-send-comment-pr/commit/aa1f74c9351dad7778c16a1676b7082a9fe8ea16

https://github.com/iterative/test-cml-send-comment-pr/runs/5198787294?check_suite_focus=true#step:4:10

**Comment by casperdcl** [comment]
Hmm AFAIK you are doing `cml send-comment` (without `--pr`) on a commit from mid-Nov last year. It could indeed be locked due to being old?

Does using `cml send-comment --pr` work instead?

**Comment by 0x2b3bfa0** [comment]
https://github.community/t/comment-api-does-not-describe-commit-id-has-been-locked/159853/2

**Comment by daavoo** [comment]
> Try using a personal access token instead of [GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication)

For the record, adding a PAT token with `repo` & `workflow` permissions has solved the issue.

However, it feels a little cumbersome to do this "only" to enable `--update`, while "no-update" works with the default token

**Comment by casperdcl** [comment]
[this](https://github.com/iterative/cml/issues/888#issuecomment-1152312400) should be documented
