### ISSUE TITLE
Github Runner not working on MACOS

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#904]
Now the runner download for MACOS is not working due to the project change

```sh
info: Launching github runner
error: Error: Failed preparing GitHub runner: zlib: invalid stored block lengths
    at Github.startRunner (/Users/davidgortega/Documents/projects/@iterative/cml/src/drivers/github.js:284:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async CML.startRunner (/Users/davidgortega/Documents/projects/@iterative/cml/src/cml.js:285:12)
    at async runLocal (/Users/davidgortega/Documents/projects/@iterative/cml/bin/cml/runner.js:237:16)
    at async run (/Users/davidgortega/Documents/projects/@iterative/cml/bin/cml/runner.js:388:8)
    at async Object.exports.handler (/Users/davidgortega/Documents/projects/@iterative/cml/bin/cml/runner.js:401:5) {"status":"terminated"}
```

**Comment by DavidGOrtega** [comment]
The runner releases have changed indeed but the link still working. Seems to be a transient error.

**Comment by 0x2b3bfa0** [comment]
😅

**Comment by DavidGOrtega** [comment]
No, its still there. Something is happening with the MACOS package

**Comment by dacbd** [comment]
my daily pulse ran fine.
<details>

```
2022-02-28T16:05:41.1552425Z Requested labels: ubuntu-latest
2022-02-28T16:05:41.1552480Z Job defined at: 
2022-02-28T16:05:41.1552506Z Waiting for a runner to pick up this job...
2022-02-28T16:05:42.7190469Z Job is waiting for a hosted runner to come online.
2022-02-28T16:06:11.7447507Z Job is about to start running on the hosted runner: GitHub Actions 2 (hosted)
2022-02-28T16:06:15.8093581Z Current runner version: '2.287.1'
2022-02-28T16:06:15.8128947Z ##[group]Operating System
2022-02-28T16:06:15.8129826Z Ubuntu
2022-02-28T16:06:15.8130305Z 20.04.3
2022-02-28T16:06:15.8131166Z LTS
2022-02-28T16:06:15.8131673Z ##[endgroup]
2022-02-28T16:06:15.8132199Z ##[group]Virtual Environment
2022-02-28T16:06:15.8133092Z Environment: ubuntu-20.04
2022-02-28T16:06:15.8133690Z Version: 20220220.1
2022-02-28T16:06:15.8134815Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20220220.1/images/linux/Ubuntu2004-Readme.md
2022-02-28T16:06:15.8135809Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20220220.1
2022-02-28T16:06:15.8136723Z ##[endgroup]
2022-02-28T16:06:15.8137292Z ##[group]Virtual Environment Provisioner
2022-02-28T16:06:15.8137857Z 1.0.0.0-main-20220215-1
2022-02-28T16:06:15.8138350Z ##[endgroup]

...

2022-02-28T16:06:15.8155668Z Secret source: Actions
2022-02-28T16:06:15.8156417Z Prepare workflow directory
2022-02-28T16:06:15.9175185Z Prepare all required actions
2022-02-28T16:06:15.9419948Z Getting action download info
2022-02-28T16:06:16.7002090Z Download action repository 'iterative/setup-cml@v1' (SHA:d20d4aafa96eaffcae0117576b03079b70b163c9)
2022-02-28T16:06:17.2341362Z Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)

```

</details>

**Comment by 0x2b3bfa0** [comment]
Tracked upstream: https://github.com/actions/runner/issues/1719

**Comment by 0x2b3bfa0** [comment]
Fixed upstream: https://github.com/actions/runner/issues/1719#issuecomment-1054587918
