### ISSUE TITLE
Gitlab Bad Gateway

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/cml#929]
Seen [here](https://gitlab.com/iterative.ai/cml/-/jobs/2273929583)
```
{"level":"error","message":"Bad Gateway","stack":"Error: Bad Gateway\n    at Gitlab.request (/usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:473:38)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:229:11\n    at async Promise.all (index 16)\n    at async Gitlab.runners (/usr/lib/node_modules/@dvcorg/cml/src/drivers/gitlab.js:224:12)\n    at async CML.runners (/usr/lib/node_modules/@dvcorg/cml/src/cml.js:292:12)\n    at async run (/usr/lib/node_modules/@dvcorg/cml/bin/cml/runner.js:383:19)\n    at async Object.exports.handler (/usr/lib/node_modules/@dvcorg/cml/bin/cml/runner.js:425:5)","status":"terminated"}
{"level":"info","message":"waiting 10 seconds before exiting..."}
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit code 1
```

**Comment by DavidGOrtega** [comment]
It seems so 😞 however It was a long window of time
